# I. NumPy.

**Оцінювання даної роботи буде ураховувати якість Вашого коду та текстових відповідей. При наявності ЛИШЕ коду , робота оцінюватися НЕ БУДЕ.**  

**Оформлення текстових відповідей повинно проводитися в текстових комірках ноутбука з використанням синтаксису [LaTeX](https://en.wikibooks.org/wiki/LaTeX/Basics) для оформлення тексту та формул.**

**Роботи ідентифіковані як ІДЕНТИЧНІ одразу отримують 0 балів.**

**При реалізації завдань потрібно використовувати методи з бібліотеки numpy та pandas.**

**Рішення з циклами будуть оцінені в 0 балів.**

0. Імпортувати numpy загальноприйнятим способом.

In [2]:
import numpy as np

1. Визначити список з оцінками студента(ки) за семестр. Використовуючи його, створити одновимірний масив numpy.

In [3]:
marks = np.array([1, 2, 3, 4, 5])

print(marks)

[1 2 3 4 5]


2. Визначити список зі списками, де кожен рядок списку формально означає магазин, а кожна колонка - певний продукт (батон, яйця першої категорії, молоко та ковбаса), а елементами на пересічі є ціни на ці продукти відповідно. Використовуючи цей список, створити матрицю (двовимірний масив) numpy.

In [4]:
market = [
    [20, 45, 30, 150],  
    [21, 44, 29, 145],  
    [19, 46, 31, 155]]

market_matrix = np.array(market)
print(market_matrix)

[[ 20  45  30 150]
 [ 21  44  29 145]
 [ 19  46  31 155]]


3. Отримайте тип даних значень з масивів завдань 2 та 3. Виведіть їх на екран.

In [5]:
data_type1 = market_matrix.dtype
data_type2 = marks.dtype
print("Type of data:", data_type1, ',', data_type2)

Type of data: int64 , int64


4. Отримайте форми (кортеж з кількістю рядків та колонок) масивів завдань 2 та 3. Виведіть їх на екран.

In [6]:
print(marks.shape)
print(market_matrix.shape)

(5,)
(3, 4)


5. Створіть одновимірний масив за допомогою спеціальної функції numpy, який би відображав динаміку стабільно зростаючого (з рівними проміжками) прибутку з продажів  за тиждень, де у перший день не було продажів, а в останній день тижня вдалося заробити 1000 грн 50 коп.

In [7]:
profit_array = np.linspace(0, 1000.50, 7)
print("Dynamics for 7 days:", profit_array)

Dynamics for 7 days: [   0.    166.75  333.5   500.25  667.    833.75 1000.5 ]


6. Створіть два масиви. Використовуючи їх, продемонструйте відмінність вертикального та горизонтального обʼєднання масивів.

In [8]:
array1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

array2 = np.array([
    [10,11,12],
    [13,14,15],
    [16,17,18]
])

vertical = np.vstack((array1, array2))
horisontal = np.hstack((array1, array2))

print(vertical,"\n")
print(horisontal)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]] 

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


7. Визначити функцію, яка приймає на вході масив і транспонує його. Скористайтесь методом reshape. І не забудьте почати з docstrings.

In [9]:
def transpose_matrix(array: np.ndarray) -> np.ndarray:
    """
    Transpose matrix using the reshape method.

    Parameters:
    array (numpy.ndarray): The input matrix to be transposed.

    Returns:
    numpy.ndarray: The transposed array.
    """
    rows, cols = array.shape
    return np.reshape(array, (cols, rows))

# Приклад використання
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("orig array: \n", array)
transposed_array = transpose_matrix(array)
print("transposed array: \n", transposed_array)


orig array: 
 [[1 2 3 4]
 [5 6 7 8]]
transposed array: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


8. Створіть два масиви. Використовучи ці масиви, продемонструйте 1) операцію по-елементного додавання, 2) операцію по-елементного віднімання, 3) множення масиву на число, 4) операцію по-елементного множення, і 5) матричного множення.

In [10]:
array1 = np.array([1, 2, 3])
array2 = np.array([7, 8, 9])

addition = array1 + array2

subtraction = array1 - array2

multiplication_by_scalar = array1 * 2

elementwise_multiplication = array1 * array2

matrix_multiplication = np.dot(array1, array2.T)

print("1:\n", addition)
print("2:\n", subtraction)
print("3:\n", multiplication_by_scalar)
print("4:\n", elementwise_multiplication)
print("5:\n", matrix_multiplication)

1:
 [ 8 10 12]
2:
 [-6 -6 -6]
3:
 [2 4 6]
4:
 [ 7 16 27]
5:
 50


9. Створіть двовимірний масив (матрицю) та розрахуйте: 1) мінімальне число, 2) максимальне число, 3) суму чисел, 4) мінімальні числа для кожного рядка, 5) максимальні числа для кожного стовпчика.

In [11]:
array = np.array([
    [1,2,3],
    [4,5,6]
])

print(array.min())
print(array.max())
print(array.sum())
print(array.min(axis=1))
print(array.max(axis=0))

1
6
21
[1 4]
[4 5 6]


10. Створіть матрицю , де деякі елементи повторюються. Знайдіть унікальні значення елементів цієї матриці та їхні частоти.

In [12]:
array = np.array([1,1,3,4,4,4,6,8,8])
print(np.unique(array, return_counts = True)[0])
print(np.unique(array, return_counts = True)[1])


[1 3 4 6 8]
[2 1 3 1 2]


# II. Importing. Creating DF

0. Імпортувати бібліотеку pandas

In [13]:
import pandas as pd

11. Створити тестовий датафрейм зі списку, що містить записи пацієнтів про їхні прізвища, імена, дату народження, масу тіла та наявність медичного страхування. Одне зі значень зробить пустим. Ознайомтесь з типом кожної колонки.

In [14]:
columns = ["Last Name", "First Name", "Date of Birth", "Weight(kg)", "Has Insurance"]

data = np.array([
    ["Popov", "Andriy", "2000-01-01", 70, True],
    ["Chernysh", "Nastya", "2001-05-12", np.nan, False],
    ["Mak", "Sasha", "2003-07-23", 50, True]
])

test_df = pd.DataFrame(data, columns=columns)

test_df["Date of Birth"] = pd.to_datetime(test_df["Date of Birth"])
test_df["Weight(kg)"] = pd.to_numeric(test_df["Weight(kg)"], errors="coerce")
test_df["Has Insurance"] = test_df["Has Insurance"].astype(bool)

print(test_df)
print(test_df.dtypes)

  Last Name First Name Date of Birth  Weight(kg)  Has Insurance
0     Popov     Andriy    2000-01-01        70.0           True
1  Chernysh     Nastya    2001-05-12         NaN           True
2       Mak      Sasha    2003-07-23        50.0           True
Last Name                object
First Name               object
Date of Birth    datetime64[ns]
Weight(kg)              float64
Has Insurance              bool
dtype: object


# III. Reading from file

12. Завантажити файл missile_attacks_daily.csv з [Kaggle](https://www.kaggle.com/datasets/piterfm/massive-missile-attacks-on-ukraine?select=missile_attacks_daily.csv). Ознайомитись з описом датасету. Додати файл до папки поточної сесії colab notebook на панелі ліворуч або на гугл диск (локально до проєкту, якщо працюєте у пайчармі). Зчитати датафрейм з файлу та вивести датафрейм на екран. Зверніть увагу на те, щоб всі колонки відповідали наведеним у описі типам даних.

In [15]:
df = pd.read_csv(".\missile_attacks_daily.csv")
print(df)
print(df.dtypes)

            time_start          time_end               model  \
0     2025-01-18 20:00  2025-01-19 09:00      Shahed-136/131   
1     2025-01-17 19:00  2025-01-18 08:00      Shahed-136/131   
2     2025-01-16 19:00  2025-01-17 09:00      Shahed-136/131   
3     2025-01-16 19:00  2025-01-17 09:00    Iskander-M/KN-23   
4     2025-01-16 19:00  2025-01-17 09:00          Iskander-M   
...                ...               ...                 ...   
2039  2022-10-01 12:00  2022-10-01 12:00            Orlan-10   
2040        2022-09-30        2022-09-30            Orlan-10   
2041  2022-09-29 23:00  2022-09-29 23:59      Shahed-136/131   
2042        2022-09-28        2022-09-28                X-59   
2043        2022-09-28        2022-09-28  Reconnaissance UAV   

                                           launch_place  \
0         Bryansk oblast and Oryol oblast and Millerovo   
1     Primorsko-Akhtarsk and Bryansk oblast and Mill...   
2     Primorsko-Akhtarsk and Kursk oblast and Bryans..

<>:1: SyntaxWarning: invalid escape sequence '\m'
<>:1: SyntaxWarning: invalid escape sequence '\m'
C:\Users\msnit\AppData\Local\Temp\ipykernel_9416\3642853674.py:1: SyntaxWarning: invalid escape sequence '\m'
  df = pd.read_csv(".\missile_attacks_daily.csv")


# IV. Data understanding

13. Виведіть на екран перші 10 рядків зчитаного датафрейму.

In [16]:
df.head(10)

time_start          time_end             model  \
0  2025-01-18 20:00  2025-01-19 09:00    Shahed-136/131   
1  2025-01-17 19:00  2025-01-18 08:00    Shahed-136/131   
2  2025-01-16 19:00  2025-01-17 09:00    Shahed-136/131   
3  2025-01-16 19:00  2025-01-17 09:00  Iskander-M/KN-23   
4  2025-01-16 19:00  2025-01-17 09:00        Iskander-M   
5  2025-01-15 20:00  2025-01-16 09:00    Shahed-136/131   
6  2025-01-15 06:00  2025-01-15 08:00         X-59/X-69   
7  2025-01-15 06:00  2025-01-15 08:00         X-22/X-32   
8  2025-01-15 06:00  2025-01-15 08:00       X-101/X-555   
9  2025-01-15 06:00  2025-01-15 08:00            Kalibr   

                                        launch_place       target  carrier  \
0      Bryansk oblast and Oryol oblast and Millerovo      Ukraine      NaN   
1  Primorsko-Akhtarsk and Bryansk oblast and Mill...      Ukraine      NaN   
2  Primorsko-Akhtarsk and Kursk oblast and Bryans...      Ukraine      NaN   
3                 Bryansk oblast and Voronezh oblast  Kyiv oblast      NaN   
4                                      Rostov oblast      Ukraine      NaN   
5  Primorsko-Akhtarsk and Bryansk oblast and Oryo...      Ukraine      NaN   
6                                    Belgorod oblast      Ukraine      NaN   
7                                        Tula oblast      Ukraine  Tu-22M3   
8                                   Volgograd oblast      Ukraine  Tu-95MS   
9                                          Black Sea      Ukraine     Navi   

   launched  destroyed  not_reach_goal  cross_border_belarus  back_russia  \
0      61.0         43            15.0                   NaN          NaN   
1      39.0         24            14.0                   NaN          NaN   
2      50.0         33             9.0                   NaN          NaN   
3       4.0          2             NaN                   NaN          NaN   
4       2.0          0             NaN                   NaN          NaN   
5      55.0         34            18.0                   NaN          NaN   
6       4.0          4             NaN                   NaN          NaN   
7       7.0          0             NaN                   NaN          NaN   
8      27.0         23             NaN                   NaN          NaN   
9       4.0          3             NaN                   NaN          NaN   

   still_attacking                                  destroyed_details  \
0              1.0  {'Mykolaiv oblast': NaN,    'Kyiv oblast': NaN...   
1              NaN  {'Kherson oblast': NaN, 'Khmelnytskyi oblast':...   
2              NaN  {'Odesa oblast and Mykolaiv oblast': 7, 'Khmel...   
3              NaN                                                NaN   
4              NaN                                                NaN   
5              NaN  {'Mykolaiv oblast': 5, 'Kyiv oblast': NaN, 'Su...   
6              NaN                                                NaN   
7              NaN                                                NaN   
8              NaN                                       {'west': 20}   
9              NaN                                       {'south': 1}   

  launched_details launch_place_details  \
0              NaN                  NaN   
1              NaN                  NaN   
2              NaN                  NaN   
3              NaN                  NaN   
4              NaN                  NaN   
5              NaN                  NaN   
6              NaN                  NaN   
7              NaN                  NaN   
8              NaN                  NaN   
9              NaN                  NaN   

                                              source  
0  kpszsu/posts/pfbid0meYNAsX4voALE4SXunVpzKTwzrJ...  
1  kpszsu/posts/pfbid0Rpzfu7u9ERu4o49Gm12eqSogKvZ...  
2  kpszsu/posts/pfbid0Gvye9Wn2gj8RPiiGaTQFGRas9Yg...  
3  kpszsu/posts/pfbid0Rpzfu7u9ERu4o49Gm12eqSogKvZ...  
4  kpszsu/posts/pfbid0Gvye9Wn2gj8RPiiGaTQFGRas9Yg...  
5  kpszsu/posts/pfbid0tPwzQHvvr63PbehDshED2W

14. Отримайте інформацію про форму датафрейму.

In [17]:
df.shape

(2044, 16)

15. Отримайте дані про кожну колонку з її назвою, типом даних та кількістю непустих значень.

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2044 entries, 0 to 2043
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   time_start            2044 non-null   object 
 1   time_end              2044 non-null   object 
 2   model                 2044 non-null   object 
 3   launch_place          1023 non-null   object 
 4   target                2016 non-null   object 
 5   carrier               225 non-null    object 
 6   launched              2041 non-null   float64
 7   destroyed             2044 non-null   int64  
 8   not_reach_goal        157 non-null    float64
 9   cross_border_belarus  32 non-null     float64
 10  back_russia           34 non-null     float64
 11  still_attacking       28 non-null     float64
 12  destroyed_details     294 non-null    object 
 13  launched_details      4 non-null      object 
 14  launch_place_details  4 non-null      object 
 15  source               

16. Отримайте статистику для колонок числового типу.

In [19]:
print(df["launched"].max())
print(df["destroyed"].mean())
print(df["back_russia"].max())

193.0
7.491682974559687
5.0


17. Отримати кількість унікальних значень у кожній колонці. Вивести на екран значення та кількість цих значень у колонці, яка має найменше унікальних значень.

In [20]:
print(df.nunique())
print(df.nunique().min())

time_start               864
time_end                1015
model                     61
launch_place             135
target                    97
carrier                   58
launched                 113
destroyed                 81
not_reach_goal            55
cross_border_belarus       7
back_russia                5
still_attacking            8
destroyed_details        290
launched_details           4
launch_place_details       4
source                   960
dtype: int64
4


18. На основі отриманої інформації про датасет вище, опишіть по пунктах, що б ви виправили або на що б звернули увагу на кроці очищення даних і чому?

**місце для текстової відповіді**

1. Duplicate removal
2. Negative or zero duration
3. Date format check
4. Missing values handling
5. Index reset


# V. Data Cleaning

19. Перетворити колонку launched у цілочислену (Int64). Перевірити, чи все пройшло, як очікувалось.

In [25]:
df["launched"] = df["launched"].astype('Int64')

print(df["launched"].dtype)
df["launched"].head(10)

Int64


0    61
1    39
2    50
3     4
4     2
5    55
6     4
7     7
8    27
9     4
Name: launched, dtype: Int64

ми не можемо конвертувати дані типу NA або inf тому нам видається помилка

20. Видалити колонки, де кількість непустих значень становить менше 30% від загальної кількості записів.

In [22]:
total_rows = df.shape[0]

threshold = total_rows * 0.3

df_cleaned = df.dropna(thresh=threshold, axis=1)

print("Оригінальний DataFrame:")
print(df.columns)

print("\nОчищений DataFrame:")
print(df_cleaned.columns)



Оригінальний DataFrame:
Index(['time_start', 'time_end', 'model', 'launch_place', 'target', 'carrier',
       'launched', 'destroyed', 'not_reach_goal', 'cross_border_belarus',
       'back_russia', 'still_attacking', 'destroyed_details',
       'launched_details', 'launch_place_details', 'source'],
      dtype='object')

Очищений DataFrame:
Index(['time_start', 'time_end', 'model', 'launch_place', 'target', 'launched',
       'destroyed', 'source'],
      dtype='object')


21. Очистити датафрейм від дублікатів (дублюючихся рядків) та записів, де атака продовжувалась відʼємну або нульову кількість часу (що фізично неможливо). Не забудьте оновити індекс. Скільки рядків було видалено? Як ви це перевірили у коді?

In [26]:
df_cleaned['time_start'] = pd.to_datetime(df_cleaned["time_start"], format="mixed")
df_cleaned['time_end'] = pd.to_datetime(df_cleaned["time_end"], format="mixed")

df_cleaned['attack_duration'] = (df_cleaned['time_end'] - df_cleaned['time_start']).dt.total_seconds()

initial_rows = df_cleaned.shape[0]
print(initial_rows)

df_cleaned = df_cleaned[df_cleaned['attack_duration'] > 0]
final_rows = df_cleaned.shape[0]

df_cleaned.reset_index(drop=True)

removed_rows = initial_rows - final_rows
print(f'Було видалено {removed_rows} рядків.')




1208
Було видалено 0 рядків.


**місце для текстової відповіді**

deleted 836 rows. we subtracted the remaining columns from the initial ones and counted how many were deleted

22. Виведіть на екран всі рядки, де є хоч одне пропущене значення.

In [24]:
print(df_cleaned.isna().count())

#every column has nan

time_start         1208
time_end           1208
model              1208
launch_place       1208
target             1208
launched           1208
destroyed          1208
source             1208
attack_duration    1208
dtype: int64
